FROM alpine:3.18
RUN apk add --update
RUN apk add --no-cache python3
RUN apk add --no-cache py3-pip
RUN pip install -U setuptools
RUN pip install gunicorn
RUN pip install flask-restful
RUN pip install flasgger
RUN pip install -U Flask-SQLAlchemy
RUN pip install -U Flask-Migrate
RUN pip install -U Flask-Mail
RUN pip install Flask-CORS
RUN pip install python-dotenv
RUN pip install requests
RUN pip install pip install Flask-APScheduler
RUN pip install gevent

RUN mkdir -p /app
WORKDIR /app
COPY . /app
RUN chmod 777 -R start_services.sh
CMD /app/start_services.sh